#!/bin/bash

CONFIG_FILE="$HOME/.config/hypr/conf/WINDOWSANDWORKSPACES.conf"

# The rules for floating
FLOAT_RULES=(
    "windowrulev2 = float, class:.*"
    "windowrulev2 = size 950 500, class:(kitty)"
    "windowrulev2 = size 950 500, class:(librewolf)"
)

# Loop through each rule and uncomment it
for RULE in "${FLOAT_RULES[@]}"; do
    # Uncomment the rule if commented
    sed -i "s/^#\($RULE\)/\1/" "$CONFIG_FILE"
    echo "Enabled float rule: $RULE"
done
